package com.example.displaymoto

data class AppStrings(
    // === COMMON ===
    val back: String, val select: String, val cancel: String, val more: String,
    val on: String, val off: String, val standard: String,
    // === SETTINGS ===
    val settingsTitle: String, val bluetoothTitle: String, val bluetoothDesc: String,
    val connectTitle: String, val connectDesc: String,
    val colorTitle: String, val colorDesc: String,
    val elemColorTitle: String, val elemColorDesc: String,
    val langTitle: String, val langDesc: String,
    val persTitle: String, val persDesc: String,
    val aboutTitle: String, val aboutDesc: String,
    val colorLibraryTitle: String, val dragColor: String,
    // === PERSONALIZATION ===
    val activateIaTitle: String, val activateIaDesc: String,
    val visualPrefTitle: String, val visualPrefDesc: String,
    val touchTitle: String, val touchDesc: String,
    val cognitiveTitle: String, val cognitiveDesc: String,
    val audioHapticsTitle: String, val audioHapticsDesc: String,
    val editIconsTitle: String, val editIconsDesc: String,
    // === VISUAL PREFERENCES ===
    val contrastTitle: String, val contrastDesc: String,
    val highContrast: String, val nightMode: String,
    val textSizeTitle: String, val textSizeDesc: String,
    val colorFiltersTitle: String, val colorFiltersDesc: String, val grayScale: String,
    val textSpacingTitle: String, val textSpacingDesc: String, val expanded: String,
    val animationsTitle: String, val animationsDesc: String, val reduced: String,
    // === TOUCH ===
    val touchSettingsTitle: String,
    val touchAreasTitle: String, val touchAreasDesc: String, val large: String, val extraLarge: String,
    val methodTitle: String, val methodDesc: String, val directTouch: String, val swipe: String, val joystick: String,
    val responseTimeTitle: String, val responseTimeDesc: String, val fast: String, val medium: String, val slow: String,
    val errorPreventionTitle: String, val errorPreventionDesc: String,
    // === COGNITIVE ===
    val langComplexityTitle: String, val langComplexityDesc: String, val simple: String, val technical: String,
    val infoDensityTitle: String, val infoDensityDesc: String, val essential: String, val full: String,
    val contextHelpTitle: String, val contextHelpDesc: String, val onDemand: String, val alwaysOn: String,
    val alertsTitle: String, val alertsDesc: String, val criticalOnly: String, val all: String,
    // === AUDIO & HAPTICS ===
    val audioHapticsScreenTitle: String, val feedbackDesc: String,
    val audio: String, val haptic: String, val both: String,
    val visualAlertsTitle: String, val visualAlertsDesc: String,
    val errorFeedbackTitle: String, val errorFeedbackDesc: String, val hapticBoost: String, val maximum: String,
    // === DASHBOARD ===
    val road3d: String, val warning: String, val lowBattery: String,
    val critRange1: String, val critRange2: String,
    // === MISC ===
    val workInProgress: String
)

enum class AppLanguage(val displayName: String) {
    EN("ENGLISH"), PT("PORTUGUÊS"), ES("ESPAÑOL"),
    FR("FRANÇAIS"), DE("DEUTSCH"), IT("ITALIANO")
}

fun getAppStrings(lang: AppLanguage): AppStrings = when (lang) {
    AppLanguage.EN -> AppStrings(
        "BACK", "SELECT", "CANCEL", "MORE+", "ON", "OFF", "STANDARD",
        "SETTINGS", "BLUETOOTH", "Manage phone and intercom connections",
        "CONNECT MYFULGORA", "Sync your motorcycle with the official app",
        "COLOUR", "Tap for full library or pick a shortcut",
        "ELEMENTS & TEXT", "Change the colour of text, lines and highlights",
        "LANGUAGE", "Select the system display language",
        "PERSONALIZATION", "Adjust display, units and layout preferences",
        "ABOUT THE MOTORCYCLE", "System information, software updates and details",
        "COLOUR LIBRARY", "Drag to pick any colour",
        "ACTIVATE ADAPTATION IA", "Enable AI-driven interface adjustments",
        "VISUAL PREFERENCES", "Adjust contrast, text size and layout colors",
        "TOUCH", "Configure screen sensitivity and gestures",
        "COGNITIVE ASSISTANT", "Simplify interface and provide guidance",
        "AUDIO AND HAPTICS", "Manage sound feedback and vibrations",
        "EDIT ICONS", "Customize dashboard layout and icon positions",
        "CONTRAST", "Adjust the display contrast ratio", "HIGH CONTRAST", "NIGHT MODE",
        "TEXT SIZE", "Change the system text size",
        "COLOR FILTERS", "Apply filters for color blindness or preference", "GRAY SCALE",
        "TEXT SPACING", "Adjust spacing between letters and lines", "EXPANDED",
        "ANIMATIONS", "Reduce or disable system animations", "REDUCED",
        "TOUCH SETTINGS",
        "TOUCH AREAS", "Adjust the minimum target size for interactive elements", "LARGE", "EXTRA LARGE",
        "METHOD OF ENTRY", "Choose your preferred way to interact with the system", "DIRECT TOUCH", "SWIPE", "JOYSTICK",
        "RESPONSE TIME", "Set the delay required to register a touch action", "FAST", "MEDIUM", "SLOW",
        "ERROR PREVENTION", "Require confirmation dialogs for critical actions",
        "LANGUAGE COMPLEXITY", "Adjust the terminology used across the system", "SIMPLE", "TECHNICAL",
        "INFORMATION DENSITY", "Control how much data is displayed on screen at once", "ESSENTIAL", "FULL",
        "CONTEXTUAL HELP", "Provide explanations for system features and warnings", "ON DEMAND", "ALWAYS ON",
        "ALERTS", "Filter the frequency and priority of system notifications", "CRITICAL ONLY", "ALL",
        "AUDIO & HAPTICS", "Choose your preferred system interaction feedback",
        "AUDIO", "HAPTIC", "BOTH",
        "VISUAL ALERTS FOR AUDIO", "Flash screen elements when important sound alerts occur",
        "ERROR FEEDBACK", "Adjust the intensity of alerts when a system error happens", "HAPTIC BOOST", "MAXIMUM",
        "3D ROAD", "W A R N I N G", "LOW BATTERY (20%)",
        "Critical range. Please proceed to", "a charging station immediately.",
        "Work in Progress..."
    )
    AppLanguage.PT -> AppStrings(
        "VOLTAR", "SELECIONAR", "CANCELAR", "MAIS+", "LIGADO", "DESLIGADO", "PADRÃO",
        "DEFINIÇÕES", "BLUETOOTH", "Gerir telemóvel e intercomunicadores",
        "CONECTAR MYFULGORA", "Sincronize a sua mota com a app oficial",
        "COR", "Toque para a biblioteca ou escolha um atalho",
        "ELEMENTOS E TEXTO", "Alterar a cor do texto, linhas e destaques",
        "IDIOMA", "Selecione o idioma de exibição do sistema",
        "PERSONALIZAÇÃO", "Ajustar ecrã, unidades e preferências",
        "SOBRE A MOTA", "Informações do sistema, atualizações e detalhes",
        "BIBLIOTECA DE CORES", "Arraste para escolher uma cor",
        "ATIVAR IA ADAPTATIVA", "Ativar ajustes automáticos da interface por IA",
        "PREFERÊNCIAS VISUAIS", "Ajustar contraste, tamanho de texto e cores",
        "TOQUE", "Configurar sensibilidade e gestos do ecrã",
        "ASSISTENTE COGNITIVO", "Simplificar interface e fornecer orientação",
        "ÁUDIO E VIBRAÇÃO", "Gerir feedback sonoro e vibrações",
        "EDITAR ÍCONES", "Personalizar layout e posição dos ícones",
        "CONTRASTE", "Ajustar o rácio de contraste do ecrã", "ALTO CONTRASTE", "MODO NOTURNO",
        "TAMANHO DO TEXTO", "Alterar o tamanho do texto do sistema",
        "FILTROS DE COR", "Aplicar filtros para daltonismo ou preferência", "ESCALA DE CINZA",
        "ESPAÇAMENTO DO TEXTO", "Ajustar espaçamento entre letras e linhas", "EXPANDIDO",
        "ANIMAÇÕES", "Reduzir ou desativar animações do sistema", "REDUZIDO",
        "DEFINIÇÕES DE TOQUE",
        "ÁREAS DE TOQUE", "Ajustar o tamanho mínimo dos elementos interativos", "GRANDE", "EXTRA GRANDE",
        "MÉTODO DE ENTRADA", "Escolha a forma preferida de interagir com o sistema", "TOQUE DIRETO", "DESLIZAR", "JOYSTICK",
        "TEMPO DE RESPOSTA", "Definir o atraso para registar uma ação de toque", "RÁPIDO", "MÉDIO", "LENTO",
        "PREVENÇÃO DE ERROS", "Exigir diálogos de confirmação para ações críticas",
        "COMPLEXIDADE DA LINGUAGEM", "Ajustar a terminologia utilizada no sistema", "SIMPLES", "TÉCNICO",
        "DENSIDADE DE INFORMAÇÃO", "Controlar a quantidade de dados visíveis no ecrã", "ESSENCIAL", "COMPLETO",
        "AJUDA CONTEXTUAL", "Fornecer explicações sobre funcionalidades e avisos", "A PEDIDO", "SEMPRE ATIVA",
        "ALERTAS", "Filtrar a frequência e prioridade das notificações", "APENAS CRÍTICOS", "TODOS",
        "ÁUDIO E VIBRAÇÃO", "Escolha o feedback preferido de interação",
        "ÁUDIO", "VIBRAÇÃO", "AMBOS",
        "ALERTAS VISUAIS PARA ÁUDIO", "Piscar elementos do ecrã em alertas sonoros importantes",
        "FEEDBACK DE ERRO", "Ajustar a intensidade dos alertas em caso de erro", "VIBRAÇÃO FORTE", "MÁXIMO",
        "ESTRADA 3D", "A V I S O", "BATERIA FRACA (20%)",
        "Autonomia crítica. Por favor, dirija-se", "a um posto de carregamento imediatamente.",
        "Em desenvolvimento..."
    )
    AppLanguage.ES -> AppStrings(
        "VOLVER", "SELECCIONAR", "CANCELAR", "MÁS+", "ACTIVADO", "DESACTIVADO", "ESTÁNDAR",
        "AJUSTES", "BLUETOOTH", "Gestionar teléfono e intercomunicadores",
        "CONECTAR MYFULGORA", "Sincroniza tu moto con la app oficial",
        "COLOR", "Toca para la biblioteca o elige un atajo",
        "ELEMENTOS Y TEXTO", "Cambiar el color del texto, líneas y resaltados",
        "IDIOMA", "Selecciona el idioma de la pantalla",
        "PERSONALIZACIÓN", "Ajustar pantalla, unidades y preferencias",
        "SOBRE LA MOTO", "Información del sistema y detalles",
        "BIBLIOTECA DE COLORES", "Arrastra para elegir un color",
        "ACTIVAR IA ADAPTATIVA", "Activar ajustes automáticos de la interfaz por IA",
        "PREFERENCIAS VISUALES", "Ajustar contraste, tamaño de texto y colores",
        "TÁCTIL", "Configurar sensibilidad y gestos de la pantalla",
        "ASISTENTE COGNITIVO", "Simplificar la interfaz y proporcionar orientación",
        "AUDIO Y VIBRACIÓN", "Gestionar retroalimentación sonora y vibraciones",
        "EDITAR ICONOS", "Personalizar diseño y posición de los iconos",
        "CONTRASTE", "Ajustar la relación de contraste de la pantalla", "ALTO CONTRASTE", "MODO NOCTURNO",
        "TAMAÑO DEL TEXTO", "Cambiar el tamaño del texto del sistema",
        "FILTROS DE COLOR", "Aplicar filtros para daltonismo o preferencia", "ESCALA DE GRISES",
        "ESPACIADO DEL TEXTO", "Ajustar el espaciado entre letras y líneas", "EXPANDIDO",
        "ANIMACIONES", "Reducir o desactivar animaciones del sistema", "REDUCIDO",
        "AJUSTES TÁCTILES",
        "ÁREAS TÁCTILES", "Ajustar el tamaño mínimo de los elementos interactivos", "GRANDE", "EXTRA GRANDE",
        "MÉTODO DE ENTRADA", "Elige tu forma preferida de interactuar con el sistema", "TOQUE DIRECTO", "DESLIZAR", "JOYSTICK",
        "TIEMPO DE RESPUESTA", "Definir el retardo para registrar una acción táctil", "RÁPIDO", "MEDIO", "LENTO",
        "PREVENCIÓN DE ERRORES", "Requiere diálogos de confirmación para acciones críticas",
        "COMPLEJIDAD DEL LENGUAJE", "Ajustar la terminología utilizada en el sistema", "SIMPLE", "TÉCNICO",
        "DENSIDAD DE INFORMACIÓN", "Controlar la cantidad de datos visibles en pantalla", "ESENCIAL", "COMPLETO",
        "AYUDA CONTEXTUAL", "Proporcionar explicaciones sobre funciones y avisos", "BAJO DEMANDA", "SIEMPRE ACTIVA",
        "ALERTAS", "Filtrar la frecuencia y prioridad de las notificaciones", "SOLO CRÍTICAS", "TODAS",
        "AUDIO Y VIBRACIÓN", "Elige tu retroalimentación preferida de interacción",
        "AUDIO", "VIBRACIÓN", "AMBOS",
        "ALERTAS VISUALES PARA AUDIO", "Parpadear elementos de pantalla en alertas sonoras",
        "FEEDBACK DE ERROR", "Ajustar la intensidad de alertas en caso de error", "VIBRACIÓN FUERTE", "MÁXIMO",
        "CARRETERA 3D", "A V I S O", "BATERÍA BAJA (20%)",
        "Autonomía crítica. Por favor, diríjase", "a una estación de carga inmediatamente.",
        "En desarrollo..."
    )
    AppLanguage.FR -> AppStrings(
        "RETOUR", "SÉLECTIONNER", "ANNULER", "PLUS+", "ACTIVÉ", "DÉSACTIVÉ", "STANDARD",
        "PARAMÈTRES", "BLUETOOTH", "Gérer téléphone et interphones",
        "CONNECTER MYFULGORA", "Synchronisez votre moto avec l'app officielle",
        "COULEUR", "Touchez pour la bibliothèque ou choisissez un raccourci",
        "ÉLÉMENTS ET TEXTE", "Modifier la couleur du texte, des lignes et des surbrillances",
        "LANGUE", "Sélectionnez la langue d'affichage du système",
        "PERSONNALISATION", "Ajuster l'affichage, les unités et les préférences",
        "À PROPOS DE LA MOTO", "Informations système, mises à jour et détails",
        "BIBLIOTHÈQUE DE COULEURS", "Glissez pour choisir une couleur",
        "ACTIVER IA ADAPTATIVE", "Activer les ajustements automatiques par IA",
        "PRÉFÉRENCES VISUELLES", "Ajuster contraste, taille du texte et couleurs",
        "TACTILE", "Configurer la sensibilité et les gestes",
        "ASSISTANT COGNITIF", "Simplifier l'interface et fournir des conseils",
        "AUDIO ET VIBRATIONS", "Gérer le retour sonore et les vibrations",
        "ÉDITER LES ICÔNES", "Personnaliser la disposition et la position des icônes",
        "CONTRASTE", "Ajuster le ratio de contraste de l'écran", "CONTRASTE ÉLEVÉ", "MODE NUIT",
        "TAILLE DU TEXTE", "Modifier la taille du texte du système",
        "FILTRES DE COULEUR", "Appliquer des filtres pour daltonisme ou préférence", "NIVEAUX DE GRIS",
        "ESPACEMENT DU TEXTE", "Ajuster l'espacement entre lettres et lignes", "ÉLARGI",
        "ANIMATIONS", "Réduire ou désactiver les animations du système", "RÉDUIT",
        "PARAMÈTRES TACTILES",
        "ZONES TACTILES", "Ajuster la taille minimale des éléments interactifs", "GRAND", "TRÈS GRAND",
        "MÉTHODE DE SAISIE", "Choisissez votre méthode d'interaction préférée", "TOUCHER DIRECT", "GLISSER", "JOYSTICK",
        "TEMPS DE RÉPONSE", "Définir le délai requis pour enregistrer un toucher", "RAPIDE", "MOYEN", "LENT",
        "PRÉVENTION DES ERREURS", "Exiger une confirmation pour les actions critiques",
        "COMPLEXITÉ DU LANGAGE", "Ajuster la terminologie utilisée dans le système", "SIMPLE", "TECHNIQUE",
        "DENSITÉ D'INFORMATION", "Contrôler la quantité de données affichées à l'écran", "ESSENTIEL", "COMPLET",
        "AIDE CONTEXTUELLE", "Fournir des explications sur les fonctions et alertes", "SUR DEMANDE", "TOUJOURS ACTIVE",
        "ALERTES", "Filtrer la fréquence et la priorité des notifications", "CRITIQUES SEULEMENT", "TOUTES",
        "AUDIO ET VIBRATIONS", "Choisissez votre retour d'interaction préféré",
        "AUDIO", "VIBRATION", "LES DEUX",
        "ALERTES VISUELLES POUR AUDIO", "Faire clignoter l'écran lors d'alertes sonores",
        "RETOUR D'ERREUR", "Ajuster l'intensité des alertes en cas d'erreur", "VIBRATION FORTE", "MAXIMUM",
        "ROUTE 3D", "A T T E N T I O N", "BATTERIE FAIBLE (20%)",
        "Autonomie critique. Veuillez vous diriger", "vers une station de recharge immédiatement.",
        "En cours de développement..."
    )
    AppLanguage.DE -> AppStrings(
        "ZURÜCK", "AUSWÄHLEN", "ABBRECHEN", "MEHR+", "EIN", "AUS", "STANDARD",
        "EINSTELLUNGEN", "BLUETOOTH", "Telefon und Gegensprechanlage verwalten",
        "MYFULGORA VERBINDEN", "Synchronisieren Sie Ihr Motorrad mit der offiziellen App",
        "FARBE", "Tippen für die Bibliothek oder wählen Sie eine Verknüpfung",
        "ELEMENTE UND TEXT", "Ändern Sie die Farbe von Text, Linien und Hervorhebungen",
        "SPRACHE", "Wählen Sie die Anzeigesprache des Systems",
        "PERSONALISIERUNG", "Anzeige, Einheiten und Layouteinstellungen anpassen",
        "ÜBER DAS MOTORRAD", "Systeminformationen, Software-Updates und Details",
        "FARBBIBLIOTHEK", "Ziehen Sie, um eine Farbe auszuwählen",
        "ADAPTIVE KI AKTIVIEREN", "KI-gesteuerte Schnittstellenanpassungen aktivieren",
        "VISUELLE EINSTELLUNGEN", "Kontrast, Textgröße und Layoutfarben anpassen",
        "BERÜHRUNG", "Bildschirmempfindlichkeit und Gesten konfigurieren",
        "KOGNITIVER ASSISTENT", "Oberfläche vereinfachen und Anleitung bieten",
        "AUDIO UND HAPTIK", "Klang-Feedback und Vibrationen verwalten",
        "SYMBOLE BEARBEITEN", "Dashboard-Layout und Symbolpositionen anpassen",
        "KONTRAST", "Das Kontrastverhältnis des Bildschirms anpassen", "HOHER KONTRAST", "NACHTMODUS",
        "TEXTGRÖSSE", "Die Textgröße des Systems ändern",
        "FARBFILTER", "Filter für Farbenblindheit oder Präferenz anwenden", "GRAUSTUFEN",
        "TEXTABSTAND", "Abstände zwischen Buchstaben und Zeilen anpassen", "ERWEITERT",
        "ANIMATIONEN", "Systemanimationen reduzieren oder deaktivieren", "REDUZIERT",
        "BERÜHRUNGSEINSTELLUNGEN",
        "BERÜHRUNGSBEREICHE", "Minimale Zielgröße für interaktive Elemente anpassen", "GROSS", "SEHR GROSS",
        "EINGABEMETHODE", "Wählen Sie Ihre bevorzugte Interaktionsmethode", "DIREKTES TIPPEN", "WISCHEN", "JOYSTICK",
        "REAKTIONSZEIT", "Verzögerung für eine Berührungsaktion festlegen", "SCHNELL", "MITTEL", "LANGSAM",
        "FEHLERVERMEIDUNG", "Bestätigungsdialoge für kritische Aktionen erforderlich",
        "SPRACHKOMPLEXITÄT", "Die im System verwendete Terminologie anpassen", "EINFACH", "TECHNISCH",
        "INFORMATIONSDICHTE", "Steuern Sie die angezeigte Datenmenge auf dem Bildschirm", "WESENTLICH", "VOLLSTÄNDIG",
        "KONTEXTHILFE", "Erklärungen zu Funktionen und Warnungen bereitstellen", "AUF ANFRAGE", "IMMER AKTIV",
        "WARNUNGEN", "Häufigkeit und Priorität der Benachrichtigungen filtern", "NUR KRITISCHE", "ALLE",
        "AUDIO UND HAPTIK", "Wählen Sie Ihr bevorzugtes Interaktions-Feedback",
        "AUDIO", "HAPTIK", "BEIDES",
        "VISUELLE WARNUNGEN FÜR AUDIO", "Bildschirmelemente bei wichtigen Alarmen blinken lassen",
        "FEHLER-FEEDBACK", "Intensität der Warnungen bei Systemfehlern anpassen", "STARKE VIBRATION", "MAXIMUM",
        "3D-STRASSE", "W A R N U N G", "BATTERIE SCHWACH (20%)",
        "Kritische Reichweite. Bitte fahren Sie", "sofort zu einer Ladestation.",
        "In Entwicklung..."
    )
    AppLanguage.IT -> AppStrings(
        "INDIETRO", "SELEZIONA", "ANNULLA", "ALTRO+", "ATTIVO", "DISATTIVO", "STANDARD",
        "IMPOSTAZIONI", "BLUETOOTH", "Gestire telefono e interfoni",
        "CONNETTI MYFULGORA", "Sincronizza la tua moto con l'app ufficiale",
        "COLORE", "Tocca per la libreria o scegli una scorciatoia",
        "ELEMENTI E TESTO", "Cambiare il colore del testo, delle linee e delle evidenziazioni",
        "LINGUA", "Seleziona la lingua di visualizzazione del sistema",
        "PERSONALIZZAZIONE", "Regolare display, unità e preferenze di layout",
        "INFORMAZIONI SULLA MOTO", "Informazioni di sistema, aggiornamenti e dettagli",
        "LIBRERIA COLORI", "Trascina per scegliere un colore",
        "ATTIVA IA ADATTIVA", "Attivare regolazioni automatiche dell'interfaccia tramite IA",
        "PREFERENZE VISIVE", "Regolare contrasto, dimensione testo e colori",
        "TOCCO", "Configurare sensibilità e gesti dello schermo",
        "ASSISTENTE COGNITIVO", "Semplificare l'interfaccia e fornire guida",
        "AUDIO E VIBRAZIONE", "Gestire feedback sonoro e vibrazioni",
        "MODIFICA ICONE", "Personalizzare layout e posizione delle icone",
        "CONTRASTO", "Regolare il rapporto di contrasto dello schermo", "ALTO CONTRASTO", "MODALITÀ NOTTE",
        "DIMENSIONE TESTO", "Modificare la dimensione del testo di sistema",
        "FILTRI COLORE", "Applicare filtri per daltonismo o preferenza", "SCALA DI GRIGI",
        "SPAZIATURA TESTO", "Regolare la spaziatura tra lettere e righe", "ESPANSO",
        "ANIMAZIONI", "Ridurre o disattivare le animazioni di sistema", "RIDOTTO",
        "IMPOSTAZIONI TOCCO",
        "AREE DI TOCCO", "Regolare la dimensione minima degli elementi interattivi", "GRANDE", "EXTRA GRANDE",
        "METODO DI INPUT", "Scegli il tuo metodo preferito per interagire", "TOCCO DIRETTO", "SCORRERE", "JOYSTICK",
        "TEMPO DI RISPOSTA", "Impostare il ritardo per registrare un'azione tattile", "VELOCE", "MEDIO", "LENTO",
        "PREVENZIONE ERRORI", "Richiedere conferma per le azioni critiche",
        "COMPLESSITÀ DEL LINGUAGGIO", "Regolare la terminologia utilizzata nel sistema", "SEMPLICE", "TECNICO",
        "DENSITÀ DELLE INFORMAZIONI", "Controllare la quantità di dati visualizzati sullo schermo", "ESSENZIALE", "COMPLETO",
        "AIUTO CONTESTUALE", "Fornire spiegazioni sulle funzioni e gli avvisi", "SU RICHIESTA", "SEMPRE ATTIVO",
        "AVVISI", "Filtrare la frequenza e la priorità delle notifiche", "SOLO CRITICI", "TUTTI",
        "AUDIO E VIBRAZIONE", "Scegli il tuo feedback di interazione preferito",
        "AUDIO", "VIBRAZIONE", "ENTRAMBI",
        "AVVISI VISIVI PER AUDIO", "Far lampeggiare lo schermo durante avvisi sonori",
        "FEEDBACK ERRORE", "Regolare l'intensità degli avvisi in caso di errore", "VIBRAZIONE FORTE", "MASSIMO",
        "STRADA 3D", "A T T E N Z I O N E", "BATTERIA SCARICA (20%)",
        "Autonomia critica. Per favore, dirigiti", "verso una stazione di ricarica immediatamente.",
        "In fase di sviluppo..."
    )
}