package com.example.displaymoto

data class AppStrings(
    // === COMMON ===
    val back: String, val select: String, val cancel: String, val more: String,
    val on: String, val off: String, val standard: String,
    // === SETTINGS ===
    val settingsTitle: String, val bluetoothTitle: String, val bluetoothDesc: String,
    val connectTitle: String, val connectDesc: String,
    val colorTitle: String, val colorDesc: String,
    val elemColorTitle: String, val elemColorDesc: String,
    val textColorTitle: String, val textColorDesc: String,
    val secTextColorTitle: String, val secTextColorDesc: String,
    val langTitle: String, val langDesc: String,
    val persTitle: String, val persDesc: String,
    val aboutTitle: String, val aboutDesc: String,
    val colorLibraryTitle: String, val dragColor: String,
    // === PERSONALIZATION ===
    val activateIaTitle: String, val activateIaDesc: String,
    val visualPrefTitle: String, val visualPrefDesc: String,
    val touchTitle: String, val touchDesc: String,
    val cognitiveTitle: String, val cognitiveDesc: String,
    val audioHapticsTitle: String, val audioHapticsDesc: String,
    val editIconsTitle: String, val editIconsDesc: String,
    // === VISUAL PREFERENCES ===
    val contrastTitle: String, val contrastDesc: String,
    val highContrast: String, val nightMode: String,
    val textSizeTitle: String, val textSizeDesc: String,
    val colorFiltersTitle: String, val colorFiltersDesc: String, val grayScale: String,
    val textSpacingTitle: String, val textSpacingDesc: String, val expanded: String,
    val animationsTitle: String, val animationsDesc: String, val reduced: String,
    // === TOUCH ===
    val touchSettingsTitle: String,
    val touchAreasTitle: String, val touchAreasDesc: String, val large: String, val extraLarge: String,
    val methodTitle: String, val methodDesc: String, val directTouch: String, val swipe: String, val joystick: String,
    val responseTimeTitle: String, val responseTimeDesc: String, val fast: String, val medium: String, val slow: String,
    val errorPreventionTitle: String, val errorPreventionDesc: String,
    // === COGNITIVE ===
    val langComplexityTitle: String, val langComplexityDesc: String, val simple: String, val technical: String,
    val infoDensityTitle: String, val infoDensityDesc: String, val essential: String, val full: String,
    val contextHelpTitle: String, val contextHelpDesc: String, val onDemand: String, val alwaysOn: String,
    val alertsTitle: String, val alertsDesc: String, val criticalOnly: String, val all: String,
    // === AUDIO & HAPTICS ===
    val audioHapticsScreenTitle: String, val feedbackDesc: String,
    val audio: String, val haptic: String, val both: String,
    val visualAlertsTitle: String, val visualAlertsDesc: String,
    val errorFeedbackTitle: String, val errorFeedbackDesc: String, val hapticBoost: String, val maximum: String,
    // === DASHBOARD ===
    val road3d: String, val warning: String, val lowBattery: String,
    val critRange1: String, val critRange2: String,
    // === TRIP COMPUTER ===
    val tripTitle: String, val tripDistance: String, val avgSpeed: String,
    val maxSpeed: String, val tripTime: String, val avgConsumption: String,
    val resetTrip: String, val regenLabel: String, val chargeTimeEst: String,
    // === INDICADORES ===
    val indReady: String, val indCharging: String, val indNeutral: String,
    val indBattery: String, val indTempBat: String, val indMinimos: String,
    val indMedios: String, val indMaximos: String, val indNeblina: String,
    val indTempMotor: String, val indBrake: String, val indMil: String,
    val indAbs: String, val indEsp: String, val indPneu: String, val indV2x: String,
    val indFullBattery: String, val indStopFirst: String,
    val indStopToGear: String, val indTurnOnToGear: String,
    // === MISC ===
    val workInProgress: String
)

enum class AppLanguage(val displayName: String) {
    EN("ENGLISH"), PT("PORTUGUÊS"), ES("ESPAÑOL"),
    FR("FRANÇAIS"), DE("DEUTSCH"), IT("ITALIANO")
}

fun getAppStrings(lang: AppLanguage): AppStrings = when (lang) {
    AppLanguage.EN -> AppStrings(
        "BACK", "SELECT", "CANCEL", "MORE+", "ON", "OFF", "STANDARD",
        "SETTINGS", "BLUETOOTH", "Manage phone and intercom connections",
        "CONNECT MYFULGORA", "Sync your motorcycle with the official app",
        "COLOUR", "Tap for full library or pick a shortcut",
        "ICONS", "Change the colour of icons",
        "TEXT COLOUR", "Change the system text colour",
        "DESCRIPTION TEXT COLOUR", "Change the colour of the small description texts",
        "LANGUAGE", "Select the system display language",
        "PERSONALIZATION", "Adjust display, units and layout preferences",
        "ABOUT THE MOTORCYCLE", "System information, software updates and details",
        "COLOUR LIBRARY", "Drag to pick any colour",
        "ACTIVATE ADAPTATION IA", "Enable AI-driven interface adjustments",
        "VISUAL PREFERENCES", "Adjust contrast, text size and layout colors",
        "TOUCH", "Configure screen sensitivity and gestures",
        "COGNITIVE ASSISTANT", "Simplify interface and provide guidance",
        "AUDIO AND HAPTICS", "Manage sound feedback and vibrations",
        "EDIT ICONS", "Customize dashboard layout and icon positions",
        "CONTRAST", "Adjust the display contrast ratio", "HIGH CONTRAST", "NIGHT MODE",
        "TEXT SIZE", "Change the system text size",
        "COLOR FILTERS", "Apply filters for color blindness or preference", "GRAY SCALE",
        "TEXT SPACING", "Adjust spacing between letters and lines", "EXPANDED",
        "ANIMATIONS", "Reduce or disable system animations", "REDUCED",
        "TOUCH SETTINGS",
        "TOUCH AREAS", "Adjust the minimum target size for interactive elements", "LARGE", "EXTRA LARGE",
        "METHOD OF ENTRY", "Choose your preferred way to interact with the system", "DIRECT TOUCH", "SWIPE", "JOYSTICK",
        "RESPONSE TIME", "Set the delay required to register a touch action", "FAST", "MEDIUM", "SLOW",
        "ERROR PREVENTION", "Require confirmation dialogs for critical actions",
        "LANGUAGE COMPLEXITY", "Adjust the terminology used across the system", "SIMPLE", "TECHNICAL",
        "INFORMATION DENSITY", "Control how much data is displayed on screen at once", "ESSENTIAL", "FULL",
        "CONTEXTUAL HELP", "Provide explanations for system features and warnings", "ON DEMAND", "ALWAYS ON",
        "ALERTS", "Filter the frequency and priority of system notifications", "CRITICAL ONLY", "ALL",
        "AUDIO & HAPTICS", "Choose your preferred system interaction feedback",
        "AUDIO", "HAPTIC", "BOTH",
        "VISUAL ALERTS FOR AUDIO", "Flash screen elements when important sound alerts occur",
        "ERROR FEEDBACK", "Adjust the intensity of alerts when a system error happens", "HAPTIC BOOST", "MAXIMUM",
        "3D ROAD", "W A R N I N G", "LOW BATTERY (20%)",
        "Critical range. Please proceed to", "a charging station immediately.",
        "TRIP", "DISTANCE", "AVG SPEED", "MAX SPEED", "TRIP TIME", "AVG CONSUMPTION", "RESET", "REGEN", "EST. CHARGE TIME",
        "MOTORCYCLE ON", "CHARGING", "NEUTRAL",
        "HV BATTERY WARNING", "HIGH BATTERY TEMPERATURE", "POSITION LIGHTS ON",
        "LOW BEAM ON", "HIGH BEAM ON", "FOG LIGHTS ON",
        "HIGH ENGINE TEMPERATURE", "BRAKE FAILURE", "ENGINE MALFUNCTION",
        "ABS FAILURE", "STABILITY CONTROL OFF", "LOW TIRE PRESSURE", "V2X ACTIVE",
        "BATTERY ALREADY FULLY CHARGED", "TURN OFF MOTORCYCLE FIRST",
        "STOP TO CHANGE GEAR", "TURN ON MOTORCYCLE FIRST",
        "Work in Progress..."
    )
    AppLanguage.PT -> AppStrings(
        "VOLTAR", "SELECIONAR", "CANCELAR", "MAIS+", "LIGADO", "DESLIGADO", "PADRÃO",
        "DEFINIÇÕES", "BLUETOOTH", "Gerir telemóvel e intercomunicadores",
        "CONECTAR MYFULGORA", "Sincronize a sua mota com a app oficial",
        "COR", "Toque para a biblioteca ou escolha um atalho",
        "ÍCONES", "Alterar a cor dos ícones",
        "COR DO TEXTO", "Alterar a cor do texto do sistema",
        "COR DO TEXTO DE DESCRIÇÃO", "Alterar a cor dos pequenos textos de descrição",
        "IDIOMA", "Selecione o idioma de exibição do sistema",
        "PERSONALIZAÇÃO", "Ajustar ecrã, unidades e preferências",
        "SOBRE A MOTA", "Informações do sistema, atualizações e detalhes",
        "BIBLIOTECA DE CORES", "Arraste para escolher uma cor",
        "ATIVAR IA ADAPTATIVA", "Ativar ajustes automáticos da interface por IA",
        "PREFERÊNCIAS VISUAIS", "Ajustar contraste, tamanho de texto e cores",
        "TOQUE", "Configurar sensibilidade e gestos do ecrã",
        "ASSISTENTE COGNITIVO", "Simplificar interface e fornecer orientação",
        "ÁUDIO E VIBRAÇÃO", "Gerir feedback sonoro e vibrações",
        "EDITAR ÍCONES", "Personalizar layout e posição dos ícones",
        "CONTRASTE", "Ajustar o rácio de contraste do ecrã", "ALTO CONTRASTE", "MODO NOTURNO",
        "TAMANHO DO TEXTO", "Alterar o tamanho do texto do sistema",
        "FILTROS DE COR", "Aplicar filtros para daltonismo ou preferência", "ESCALA DE CINZA",
        "ESPAÇAMENTO DO TEXTO", "Ajustar espaçamento entre letras e linhas", "EXPANDIDO",
        "ANIMAÇÕES", "Reduzir ou desativar animações do sistema", "REDUZIDO",
        "DEFINIÇÕES DE TOQUE",
        "ÁREAS DE TOQUE", "Ajustar o tamanho mínimo dos elementos interativos", "GRANDE", "EXTRA GRANDE",
        "MÉTODO DE ENTRADA", "Escolha a forma preferida de interagir com o sistema", "TOQUE DIRETO", "DESLIZAR", "JOYSTICK",
        "TEMPO DE RESPOSTA", "Definir o atraso para registar uma ação de toque", "RÁPIDO", "MÉDIO", "LENTO",
        "PREVENÇÃO DE ERROS", "Exigir diálogos de confirmação para ações críticas",
        "COMPLEXIDADE DA LINGUAGEM", "Ajustar a terminologia utilizada no sistema", "SIMPLES", "TÉCNICO",
        "DENSIDADE DE INFORMAÇÃO", "Controlar a quantidade de dados visíveis no ecrã", "ESSENCIAL", "COMPLETO",
        "AJUDA CONTEXTUAL", "Fornecer explicações sobre funcionalidades e avisos", "A PEDIDO", "SEMPRE ATIVA",
        "ALERTAS", "Filtrar a frequência e prioridade das notificações", "APENAS CRÍTICOS", "TODOS",
        "ÁUDIO E VIBRAÇÃO", "Escolha o feedback preferido de interação",
        "ÁUDIO", "VIBRAÇÃO", "AMBOS",
        "ALERTAS VISUAIS PARA ÁUDIO", "Piscar elementos do ecrã em alertas sonoros importantes",
        "FEEDBACK DE ERRO", "Ajustar a intensidade dos alertas em caso de erro", "VIBRAÇÃO FORTE", "MÁXIMO",
        "ESTRADA 3D", "A V I S O", "BATERIA FRACA (20%)",
        "Autonomia crítica. Por favor, dirija-se", "a um posto de carregamento imediatamente.",
        "VIAGEM", "DISTÂNCIA", "VEL. MÉDIA", "VEL. MÁXIMA", "TEMPO", "CONSUMO MÉDIO", "REINICIAR", "REGEN", "TEMPO EST. CARGA",
        "MOTO LIGADA", "A CARREGAR", "PONTO MORTO",
        "AVISO BATERIA HV", "TEMPERATURA BATERIA ELEVADA", "MÍNIMOS LIGADOS",
        "MÉDIOS LIGADOS", "MÁXIMOS LIGADOS", "FARÓIS DE NEVOEIRO",
        "TEMPERATURA MOTOR ELEVADA", "FALHA NOS TRAVÕES", "AVARIA MOTOR",
        "FALHA ABS", "ESTABILIDADE DESATIVADA", "PRESSÃO PNEU BAIXA", "V2X ATIVO",
        "BATERIA JÁ FOI CARREGADA", "DESLIGUE A MOTA PRIMEIRO",
        "PARE PARA MUDAR DE MARCHA", "LIGUE A MOTA PRIMEIRO",
        "Em desenvolvimento..."
    )
    AppLanguage.ES -> AppStrings(
        "VOLVER", "SELECCIONAR", "CANCELAR", "MÁS+", "ACTIVADO", "DESACTIVADO", "ESTÁNDAR",
        "AJUSTES", "BLUETOOTH", "Gestionar teléfono e intercomunicadores",
        "CONECTAR MYFULGORA", "Sincroniza tu moto con la app oficial",
        "COLOR", "Toca para la biblioteca o elige un atajo",
        "ICONOS", "Cambiar el color de los iconos",
        "COLOR DEL TEXTO", "Cambiar el color del texto del sistema",
        "COLOR DEL TEXTO DE DESCRIPCIÓN", "Cambiar el color de los textos pequeños de descripción",
        "IDIOMA", "Selecciona el idioma de la pantalla",
        "PERSONALIZACIÓN", "Ajustar pantalla, unidades y preferencias",
        "SOBRE LA MOTO", "Información del sistema y detalles",
        "BIBLIOTECA DE COLORES", "Arrastra para elegir un color",
        "ACTIVAR IA ADAPTATIVA", "Activar ajustes automáticos de la interfaz por IA",
        "PREFERENCIAS VISUALES", "Ajustar contraste, tamaño de texto y colores",
        "TÁCTIL", "Configurar sensibilidad y gestos de la pantalla",
        "ASISTENTE COGNITIVO", "Simplificar la interfaz y proporcionar orientación",
        "AUDIO Y VIBRACIÓN", "Gestionar retroalimentación sonora y vibraciones",
        "EDITAR ICONOS", "Personalizar diseño y posición de los iconos",
        "CONTRASTE", "Ajustar la relación de contraste de la pantalla", "ALTO CONTRASTE", "MODO NOCTURNO",
        "TAMAÑO DEL TEXTO", "Cambiar el tamaño del texto del sistema",
        "FILTROS DE COLOR", "Aplicar filtros para daltonismo o preferencia", "ESCALA DE GRISES",
        "ESPACIADO DEL TEXTO", "Ajustar el espaciado entre letras y líneas", "EXPANDIDO",
        "ANIMACIONES", "Reducir o desactivar animaciones del sistema", "REDUCIDO",
        "AJUSTES TÁCTILES",
        "ÁREAS TÁCTILES", "Ajustar el tamaño mínimo de los elementos interactivos", "GRANDE", "EXTRA GRANDE",
        "MÉTODO DE ENTRADA", "Elige tu forma preferida de interactuar con el sistema", "TOQUE DIRECTO", "DESLIZAR", "JOYSTICK",
        "TIEMPO DE RESPUESTA", "Definir el retardo para registrar una acción táctil", "RÁPIDO", "MEDIO", "LENTO",
        "PREVENCIÓN DE ERRORES", "Requiere diálogos de confirmación para acciones críticas",
        "COMPLEJIDAD DEL LENGUAJE", "Ajustar la terminología utilizada en el sistema", "SIMPLE", "TÉCNICO",
        "DENSIDAD DE INFORMACIÓN", "Controlar la cantidad de datos visibles en pantalla", "ESENCIAL", "COMPLETO",
        "AYUDA CONTEXTUAL", "Proporcionar explicaciones sobre funciones y avisos", "BAJO DEMANDA", "SIEMPRE ACTIVA",
        "ALERTAS", "Filtrar la frecuencia y prioridad de las notificaciones", "SOLO CRÍTICAS", "TODAS",
        "AUDIO Y VIBRACIÓN", "Elige tu retroalimentación preferida de interacción",
        "AUDIO", "VIBRACIÓN", "AMBOS",
        "ALERTAS VISUALES PARA AUDIO", "Parpadear elementos de pantalla en alertas sonoras",
        "FEEDBACK DE ERROR", "Ajustar la intensidad de alertas en caso de error", "VIBRACIÓN FUERTE", "MÁXIMO",
        "CARRETERA 3D", "A V I S O", "BATERÍA BAJA (20%)",
        "Autonomía crítica. Por favor, diríjase", "a una estación de carga inmediatamente.",
        "VIAJE", "DISTANCIA", "VEL. MEDIA", "VEL. MÁXIMA", "TIEMPO", "CONSUMO MEDIO", "REINICIAR", "REGEN", "TIEMPO EST. CARGA",
        "MOTO ENCENDIDA", "CARGANDO", "PUNTO MUERTO",
        "AVISO BATERÍA HV", "TEMPERATURA BATERÍA ELEVADA", "LUCES DE POSICIÓN",
        "LUCES CORTAS", "LUCES LARGAS", "LUCES ANTINIEBLA",
        "TEMPERATURA MOTOR ELEVADA", "FALLO DE FRENOS", "AVERÍA MOTOR",
        "FALLO ABS", "ESTABILIDAD DESACTIVADA", "PRESIÓN NEUMÁTICO BAJA", "V2X ACTIVO",
        "BATERÍA YA CARGADA", "APAGUE LA MOTO PRIMERO",
        "DETÉNGASE PARA CAMBIAR", "ENCIENDA LA MOTO PRIMERO",
        "En desarrollo..."
    )
    AppLanguage.FR -> AppStrings(
        "RETOUR", "SÉLECTIONNER", "ANNULER", "PLUS+", "ACTIVÉ", "DÉSACTIVÉ", "STANDARD",
        "PARAMÈTRES", "BLUETOOTH", "Gérer téléphone et interphones",
        "CONNECTER MYFULGORA", "Synchronisez votre moto avec l'app officielle",
        "COULEUR", "Touchez pour la bibliothèque ou choisissez un raccourci",
        "ICÔNES", "Modifier la couleur des icônes",
        "COULEUR DU TEXTE", "Modifier la couleur du texte du système",
        "COULEUR DU TEXTE DE DESCRIPTION", "Modifier la couleur des petits textes de description",
        "LANGUE", "Sélectionnez la langue d'affichage du système",
        "PERSONNALISATION", "Ajuster l'affichage, les unités et les préférences",
        "À PROPOS DE LA MOTO", "Informations système, mises à jour et détails",
        "BIBLIOTHÈQUE DE COULEURS", "Glissez pour choisir une couleur",
        "ACTIVER IA ADAPTATIVE", "Activer les ajustements automatiques par IA",
        "PRÉFÉRENCES VISUELLES", "Ajuster contraste, taille du texte et couleurs",
        "TACTILE", "Configurer la sensibilité et les gestes",
        "ASSISTANT COGNITIF", "Simplifier l'interface et fournir des conseils",
        "AUDIO ET VIBRATIONS", "Gérer le retour sonore et les vibrations",
        "ÉDITER LES ICÔNES", "Personnaliser la disposition et la position des icônes",
        "CONTRASTE", "Ajuster le ratio de contraste de l'écran", "CONTRASTE ÉLEVÉ", "MODE NUIT",
        "TAILLE DU TEXTE", "Modifier la taille du texte du système",
        "FILTRES DE COULEUR", "Appliquer des filtres pour daltonisme ou préférence", "NIVEAUX DE GRIS",
        "ESPACEMENT DU TEXTE", "Ajuster l'espacement entre lettres et lignes", "ÉLARGI",
        "ANIMATIONS", "Réduire ou désactiver les animations du système", "RÉDUIT",
        "PARAMÈTRES TACTILES",
        "ZONES TACTILES", "Ajuster la taille minimale des éléments interactifs", "GRAND", "TRÈS GRAND",
        "MÉTHODE DE SAISIE", "Choisissez votre méthode d'interaction préférée", "TOUCHER DIRECT", "GLISSER", "JOYSTICK",
        "TEMPS DE RÉPONSE", "Définir le délai requis pour enregistrer un toucher", "RAPIDE", "MOYEN", "LENT",
        "PRÉVENTION DES ERREURS", "Exiger une confirmation pour les actions critiques",
        "COMPLEXITÉ DU LANGAGE", "Ajuster la terminologie utilisée dans le système", "SIMPLE", "TECHNIQUE",
        "DENSITÉ D'INFORMATION", "Contrôler la quantité de données affichées à l'écran", "ESSENTIEL", "COMPLET",
        "AIDE CONTEXTUELLE", "Fournir des explications sur les fonctions et alertes", "SUR DEMANDE", "TOUJOURS ACTIVE",
        "ALERTES", "Filtrer la fréquence et la priorité des notifications", "CRITIQUES SEULEMENT", "TOUTES",
        "AUDIO ET VIBRATIONS", "Choisissez votre retour d'interaction préféré",
        "AUDIO", "VIBRATION", "LES DEUX",
        "ALERTES VISUELLES POUR AUDIO", "Faire clignoter l'écran lors d'alertes sonores",
        "RETOUR D'ERREUR", "Ajuster l'intensité des alertes en cas d'erreur", "VIBRATION FORTE", "MAXIMUM",
        "ROUTE 3D", "A T T E N T I O N", "BATTERIE FAIBLE (20%)",
        "Autonomie critique. Veuillez vous diriger", "vers une station de recharge immédiatement.",
        "TRAJET", "DISTANCE", "VIT. MOYENNE", "VIT. MAXIMALE", "DURÉE", "CONSO. MOYENNE", "RÉINITIALISER", "RÉCUP.", "TEMPS EST. CHARGE",
        "MOTO ALLUMÉE", "EN CHARGE", "POINT MORT",
        "ALERTE BATTERIE HV", "TEMPÉRATURE BATTERIE ÉLEVÉE", "FEUX DE POSITION",
        "FEUX DE CROISEMENT", "FEUX DE ROUTE", "FEUX DE BROUILLARD",
        "TEMPÉRATURE MOTEUR ÉLEVÉE", "DÉFAILLANCE DES FREINS", "PANNE MOTEUR",
        "DÉFAILLANCE ABS", "STABILITÉ DÉSACTIVÉE", "PRESSION PNEU BASSE", "V2X ACTIF",
        "BATTERIE DÉJÀ CHARGÉE", "ÉTEIGNEZ D'ABORD LA MOTO",
        "ARRÊTEZ POUR CHANGER", "ALLUMEZ D'ABORD LA MOTO",
        "En cours de développement..."
    )
    AppLanguage.DE -> AppStrings(
        "ZURÜCK", "AUSWÄHLEN", "ABBRECHEN", "MEHR+", "EIN", "AUS", "STANDARD",
        "EINSTELLUNGEN", "BLUETOOTH", "Telefon und Gegensprechanlage verwalten",
        "MYFULGORA VERBINDEN", "Synchronisieren Sie Ihr Motorrad mit der offiziellen App",
        "FARBE", "Tippen für die Bibliothek oder wählen Sie eine Verknüpfung",
        "SYMBOLE", "Farbe der Symbole ändern",
        "TEXTFARBE", "Die Textfarbe des Systems ändern",
        "BESCHREIBUNGSTEXTFARBE", "Farbe der kleinen Beschreibungstexte ändern",
        "SPRACHE", "Wählen Sie die Anzeigesprache des Systems",
        "PERSONALISIERUNG", "Anzeige, Einheiten und Layouteinstellungen anpassen",
        "ÜBER DAS MOTORRAD", "Systeminformationen, Software-Updates und Details",
        "FARBBIBLIOTHEK", "Ziehen Sie, um eine Farbe auszuwählen",
        "ADAPTIVE KI AKTIVIEREN", "KI-gesteuerte Schnittstellenanpassungen aktivieren",
        "VISUELLE EINSTELLUNGEN", "Kontrast, Textgröße und Layoutfarben anpassen",
        "BERÜHRUNG", "Bildschirmempfindlichkeit und Gesten konfigurieren",
        "KOGNITIVER ASSISTENT", "Oberfläche vereinfachen und Anleitung bieten",
        "AUDIO UND HAPTIK", "Klang-Feedback und Vibrationen verwalten",
        "SYMBOLE BEARBEITEN", "Dashboard-Layout und Symbolpositionen anpassen",
        "KONTRAST", "Das Kontrastverhältnis des Bildschirms anpassen", "HOHER KONTRAST", "NACHTMODUS",
        "TEXTGRÖSSE", "Die Textgröße des Systems ändern",
        "FARBFILTER", "Filter für Farbenblindheit oder Präferenz anwenden", "GRAUSTUFEN",
        "TEXTABSTAND", "Abstände zwischen Buchstaben und Zeilen anpassen", "ERWEITERT",
        "ANIMATIONEN", "Systemanimationen reduzieren oder deaktivieren", "REDUZIERT",
        "BERÜHRUNGSEINSTELLUNGEN",
        "BERÜHRUNGSBEREICHE", "Minimale Zielgröße für interaktive Elemente anpassen", "GROSS", "SEHR GROSS",
        "EINGABEMETHODE", "Wählen Sie Ihre bevorzugte Interaktionsmethode", "DIREKTES TIPPEN", "WISCHEN", "JOYSTICK",
        "REAKTIONSZEIT", "Verzögerung für eine Berührungsaktion festlegen", "SCHNELL", "MITTEL", "LANGSAM",
        "FEHLERVERMEIDUNG", "Bestätigungsdialoge für kritische Aktionen erforderlich",
        "SPRACHKOMPLEXITÄT", "Die im System verwendete Terminologie anpassen", "EINFACH", "TECHNISCH",
        "INFORMATIONSDICHTE", "Steuern Sie die angezeigte Datenmenge auf dem Bildschirm", "WESENTLICH", "VOLLSTÄNDIG",
        "KONTEXTHILFE", "Erklärungen zu Funktionen und Warnungen bereitstellen", "AUF ANFRAGE", "IMMER AKTIV",
        "WARNUNGEN", "Häufigkeit und Priorität der Benachrichtigungen filtern", "NUR KRITISCHE", "ALLE",
        "AUDIO UND HAPTIK", "Wählen Sie Ihr bevorzugtes Interaktions-Feedback",
        "AUDIO", "HAPTIK", "BEIDES",
        "VISUELLE WARNUNGEN FÜR AUDIO", "Bildschirmelemente bei wichtigen Alarmen blinken lassen",
        "FEHLER-FEEDBACK", "Intensität der Warnungen bei Systemfehlern anpassen", "STARKE VIBRATION", "MAXIMUM",
        "3D-STRASSE", "W A R N U N G", "BATTERIE SCHWACH (20%)",
        "Kritische Reichweite. Bitte fahren Sie", "sofort zu einer Ladestation.",
        "FAHRT", "STRECKE", "Ø GESCHW.", "MAX GESCHW.", "FAHRZEIT", "Ø VERBRAUCH", "ZURÜCKSETZEN", "REKU.", "LADEZEIT GESCHÄTZT",
        "MOTORRAD EIN", "WIRD GELADEN", "LEERLAUF",
        "HV-BATTERIE WARNUNG", "HOHE BATTERIETEMPERATUR", "STANDLICHT EIN",
        "ABBLENDLICHT EIN", "FERNLICHT EIN", "NEBELSCHEINWERFER EIN",
        "HOHE MOTORTEMPERATUR", "BREMSVERSAGEN", "MOTORSTÖRUNG",
        "ABS-AUSFALL", "STABILITÄT DEAKTIVIERT", "REIFENDRUCK NIEDRIG", "V2X AKTIV",
        "BATTERIE BEREITS VOLL GELADEN", "MOTORRAD ZUERST AUSSCHALTEN",
        "ZUM SCHALTEN ANHALTEN", "MOTORRAD ZUERST EINSCHALTEN",
        "In Entwicklung..."
    )
    AppLanguage.IT -> AppStrings(
        "INDIETRO", "SELEZIONA", "ANNULLA", "ALTRO+", "ATTIVO", "DISATTIVO", "STANDARD",
        "IMPOSTAZIONI", "BLUETOOTH", "Gestire telefono e interfoni",
        "CONNETTI MYFULGORA", "Sincronizza la tua moto con l'app ufficiale",
        "COLORE", "Tocca per la libreria o scegli una scorciatoia",
        "ICONE", "Cambiare il colore delle icone",
        "COLORE DEL TESTO", "Cambiare il colore del test di sistema",
        "COLORE DEL TESTO DESCRITTIVO", "Cambiare il colore dei piccoli testi di descrizione",
        "LINGUA", "Seleziona la lingua di visualizzazione del sistema",
        "PERSONALIZZAZIONE", "Regolare display, unità e preferenze di layout",
        "INFORMAZIONI SULLA MOTO", "Informazioni di sistema, aggiornamenti e dettagli",
        "LIBRERIA COLORI", "Trascina per scegliere un colore",
        "ATTIVA IA ADATTIVA", "Attivare regolazioni automatiche dell'interfaccia tramite IA",
        "PREFERENZE VISIVE", "Regolare contrasto, dimensione testo e colori",
        "TOCCO", "Configurare sensibilità e gesti dello schermo",
        "ASSISTENTE COGNITIVO", "Semplificare l'interfaccia e fornire guida",
        "AUDIO E VIBRAZIONE", "Gestire feedback sonoro e vibrazioni",
        "MODIFICA ICONE", "Personalizzare layout e posizione delle icone",
        "CONTRASTO", "Regolare il rapporto di contrasto dello schermo", "ALTO CONTRASTO", "MODALITÀ NOTTE",
        "DIMENSIONE TESTO", "Modificare la dimensione del testo di sistema",
        "FILTRI COLORE", "Applicare filtri per daltonismo o preferenza", "SCALA DI GRIGI",
        "SPAZIATURA TESTO", "Regolare la spaziatura tra lettere e righe", "ESPANSO",
        "ANIMAZIONI", "Ridurre o disattivare le animazioni di sistema", "RIDOTTO",
        "IMPOSTAZIONI TOCCO",
        "AREE DI TOCCO", "Regolare la dimensione minima degli elementi interattivi", "GRANDE", "EXTRA GRANDE",
        "METODO DI INPUT", "Scegli il tuo metodo preferito per interagire", "TOCCO DIRETTO", "SCORRERE", "JOYSTICK",
        "TEMPO DI RISPOSTA", "Impostare il ritardo per registrare un'azione tattile", "VELOCE", "MEDIO", "LENTO",
        "PREVENZIONE ERRORI", "Richiedere conferma per le azioni critiche",
        "COMPLESSITÀ DEL LINGUAGGIO", "Regolare la terminologia utilizzata nel sistema", "SEMPLICE", "TECNICO",
        "DENSITÀ DELLE INFORMAZIONI", "Controllare la quantità di dati visualizzati sullo schermo", "ESSENZIALE", "COMPLETO",
        "AIUTO CONTESTUALE", "Fornire spiegazioni sulle funzioni e gli avvisi", "SU RICHIESTA", "SEMPRE ATTIVO",
        "AVVISI", "Filtrare la frequenza e la priorità delle notifiche", "SOLO CRITICI", "TUTTI",
        "AUDIO E VIBRAZIONE", "Scegli il tuo feedback di interazione preferito",
        "AUDIO", "VIBRAZIONE", "ENTRAMBI",
        "AVVISI VISIVI PER AUDIO", "Far lampeggiare lo schermo durante avvisi sonori",
        "FEEDBACK ERRORE", "Regolare l'intensità degli avvisi in caso di errore", "VIBRAZIONE FORTE", "MASSIMO",
        "STRADA 3D", "A T T E N Z I O N E", "BATTERIA SCARICA (20%)",
        "Autonomia critica. Per favore, dirigiti", "verso una stazione di ricarica immediatamente.",
        "VIAGGIO", "DISTANZA", "VEL. MEDIA", "VEL. MASSIMA", "TEMPO", "CONSUMO MEDIO", "RESET", "REGEN", "TEMPO ST. CARICA",
        "MOTO ACCESA", "IN CARICA", "FOLLE",
        "ALLARME BATTERIA HV", "TEMPERATURA BATTERIA ELEVATA", "LUCI DI POSIZIONE",
        "ANABBAGLIANTI", "ABBAGLIANTI", "FENDINEBBIA",
        "TEMPERATURA MOTORE ELEVATA", "GUASTO FRENI", "GUASTO MOTORE",
        "GUASTO ABS", "STABILITÀ DISATTIVATA", "PRESSIONE PNEUMATICO BASSA", "V2X ATTIVO",
        "BATTERIA GIÀ CARICA", "SPEGNERE PRIMA LA MOTO",
        "FERMARSI PER CAMBIARE", "ACCENDERE PRIMA LA MOTO",
        "In fase di sviluppo..."
    )
}

fun adaptToLanguageComplexity(base: AppStrings, complexity: String, lang: AppLanguage): AppStrings {
    if (complexity == "STANDARD") return base
    return when (lang) {
        AppLanguage.EN -> when (complexity) {
            "SIMPLE" -> base.copy(
                settingsTitle = "SETTINGS", bluetoothTitle = "PHONE", bluetoothDesc = "Connect your phone or headset",
                connectTitle = "LINK APP", connectDesc = "Link your motorcycle to the app",
                colorTitle = "COLOUR", colorDesc = "Pick a colour you like",
                elemColorTitle = "ICON COLOUR", elemColorDesc = "Pick a colour for icons",
                textColorTitle = "TEXT COLOUR", textColorDesc = "Pick a colour for text",
                secTextColorTitle = "SMALL TEXT COLOUR", secTextColorDesc = "Pick a colour for small text",
                langTitle = "LANGUAGE", langDesc = "Choose your language",
                persTitle = "LOOK & FEEL", persDesc = "Change how things look",
                aboutTitle = "ABOUT", aboutDesc = "Info about your motorcycle",
                colorLibraryTitle = "PICK A COLOUR", dragColor = "Slide to pick a colour",
                activateIaTitle = "SMART HELP", activateIaDesc = "Let the system help you automatically",
                visualPrefTitle = "SCREEN LOOK", visualPrefDesc = "Change colours and text size",
                touchTitle = "TOUCH", touchDesc = "Change how the screen responds to touch",
                cognitiveTitle = "READING HELP", cognitiveDesc = "Make the screen easier to read",
                audioHapticsTitle = "SOUNDS", audioHapticsDesc = "Change sounds and vibrations",
                editIconsTitle = "MOVE ICONS", editIconsDesc = "Move icons around",
                contrastTitle = "BRIGHTNESS", contrastDesc = "Make text easier to see",
                textSizeTitle = "TEXT SIZE", textSizeDesc = "Make text bigger or smaller",
                colorFiltersTitle = "COLOUR HELP", colorFiltersDesc = "Help with colour vision",
                textSpacingTitle = "LETTER SPACING", textSpacingDesc = "Add more space between letters",
                animationsTitle = "EFFECTS", animationsDesc = "Turn off moving effects",
                touchSettingsTitle = "TOUCH SETTINGS", touchAreasTitle = "BUTTON SIZE", touchAreasDesc = "Make buttons bigger",
                methodTitle = "HOW TO USE", methodDesc = "Choose how to use the screen",
                responseTimeTitle = "SPEED", responseTimeDesc = "How fast the screen reacts to your touch",
                errorPreventionTitle = "SAFETY CHECK", errorPreventionDesc = "Ask before doing important things",
                langComplexityTitle = "WORD DIFFICULTY", langComplexityDesc = "Use simpler or harder words",
                infoDensityTitle = "HOW MUCH INFO", infoDensityDesc = "Show more or less info on screen",
                contextHelpTitle = "TIPS", contextHelpDesc = "Show tips about what things do",
                alertsTitle = "WARNINGS", alertsDesc = "Choose which warnings to see",
                audioHapticsScreenTitle = "SOUNDS & VIBRATIONS", feedbackDesc = "Choose sounds or vibrations you feel",
                visualAlertsTitle = "SCREEN FLASH", visualAlertsDesc = "Flash the screen for important sounds",
                errorFeedbackTitle = "WARNING STRENGTH", errorFeedbackDesc = "How strong the warning feels",
                lowBattery = "BATTERY LOW (20%)", critRange1 = "Battery almost empty. Please go to", critRange2 = "a charging point now.",
                indBattery = "BATTERY PROBLEM", indTempBat = "BATTERY TOO HOT", indTempMotor = "ENGINE TOO HOT",
                indBrake = "BRAKE PROBLEM", indMil = "ENGINE PROBLEM", indAbs = "ABS PROBLEM",
                indEsp = "STABILITY HELP OFF", indPneu = "FLAT TYRE",
                indFullBattery = "BATTERY IS FULL", indStopFirst = "STOP THE MOTORCYCLE FIRST",
                indStopToGear = "STOP TO CHANGE GEAR", indTurnOnToGear = "TURN ON THE MOTORCYCLE FIRST",
                tripTitle = "RIDE INFO", tripDistance = "HOW FAR", avgSpeed = "AVERAGE SPEED", maxSpeed = "TOP SPEED", tripTime = "TIME", avgConsumption = "ENERGY USED", resetTrip = "START OVER", regenLabel = "ENERGY BACK", chargeTimeEst = "TIME LEFT",
                workInProgress = "Coming soon..."
            )
            "TECHNICAL" -> base.copy(
                settingsTitle = "SYSTEM CONFIG", bluetoothTitle = "BT PAIRING", bluetoothDesc = "Manage BT 5.0 pairing & intercom links",
                connectTitle = "OTA SYNC", connectDesc = "OTA sync via MyFulgora telemetry bridge",
                colorTitle = "BG COLOUR (HEX)", colorDesc = "Select HEX/HSL background from palette",
                elemColorTitle = "UI TINT", elemColorDesc = "Modify UI element & icon tint values",
                textColorTitle = "PRIMARY TEXT RGB", textColorDesc = "Set primary text RGB colour channel",
                secTextColorTitle = "SECONDARY TEXT RGB", secTextColorDesc = "Configure secondary text colour output",
                langTitle = "LOCALE", langDesc = "Set system locale & display language",
                persTitle = "HMI CONFIG", persDesc = "Configure HMI layout, units & scaling",
                aboutTitle = "SYSTEM DIAGNOSTICS", aboutDesc = "ECU firmware, VIN, CAN bus diagnostics",
                colorLibraryTitle = "HUE SPECTRUM", dragColor = "Drag across hue spectrum (0-360°)",
                activateIaTitle = "ML ADAPTIVE UI", activateIaDesc = "Enable ML-driven adaptive UI pipeline",
                visualPrefTitle = "VISUAL PARAMETERS", visualPrefDesc = "Configure WCAG contrast, font scaling & filters",
                touchTitle = "INPUT CALIBRATION", touchDesc = "Calibrate capacitive input & gesture recognition",
                cognitiveTitle = "COGNITIVE LOAD", cognitiveDesc = "Adjust HMI cognitive load parameters",
                audioHapticsTitle = "I/O FEEDBACK", audioHapticsDesc = "Configure audio/haptic feedback channels",
                editIconsTitle = "CLUSTER LAYOUT", editIconsDesc = "Rearrange instrument cluster widget grid",
                contrastTitle = "CONTRAST RATIO", contrastDesc = "Set WCAG 2.1 AAA luminance contrast ratio",
                textSizeTitle = "FONT SCALE (SP)", textSizeDesc = "Adjust global font scale factor (dp/sp)",
                colorFiltersTitle = "CVD MATRICES", colorFiltersDesc = "Apply CVD simulation matrices (protanopia/deuteranopia)",
                textSpacingTitle = "TYPOGRAPHIC SPACING", textSpacingDesc = "Modify letter-spacing & line-height (em units)",
                animationsTitle = "ANIM MULTIPLIER", animationsDesc = "Configure animation duration multiplier",
                touchSettingsTitle = "INPUT PARAMETERS", touchAreasTitle = "TARGET SIZE (DP)", touchAreasDesc = "Set minimum WCAG target size (44dp/48dp)",
                methodTitle = "INPUT MODALITY", methodDesc = "Select primary input modality (capacitive/swipe/HW)",
                responseTimeTitle = "DEBOUNCE (MS)", responseTimeDesc = "Configure touch debounce threshold (ms)",
                errorPreventionTitle = "CONFIRMATION DIALOGS", errorPreventionDesc = "Enable confirmation dialogs for critical CAN commands",
                langComplexityTitle = "TERMINOLOGY REGISTER", langComplexityDesc = "Set terminology register (plain/standard/technical)",
                infoDensityTitle = "TELEMETRY DENSITY", infoDensityDesc = "Configure telemetry data density level",
                contextHelpTitle = "INLINE DOCS", contextHelpDesc = "Toggle inline contextual HMI documentation",
                alertsTitle = "DTC FILTER", alertsDesc = "Set DTC notification priority filter threshold",
                audioHapticsScreenTitle = "I/O FEEDBACK CONFIG", feedbackDesc = "Select system I/O feedback modality",
                visualAlertsTitle = "VISUAL DTC FLASH", visualAlertsDesc = "Enable visual flash-on-audio DTC alerts",
                errorFeedbackTitle = "HAPTIC INTENSITY", errorFeedbackDesc = "Set haptic actuator intensity for DTC events",
                lowBattery = "HV PACK SOC CRITICAL (≤20%)", critRange1 = "SOC below minimum threshold. Navigate to", critRange2 = "nearest EVSE charging infrastructure.",
                indBattery = "HV BATTERY FAULT — DTC P0A80", indTempBat = "PACK THERMAL RUNAWAY RISK", indTempMotor = "COOLANT TEMP EXCEEDS THRESHOLD",
                indBrake = "HYDRAULIC BRAKE CIRCUIT FAILURE", indMil = "MIL — POWERTRAIN DTC ACTIVE", indAbs = "ABS MODULE FAULT — DTC C0035",
                indEsp = "ESC/TCS DEACTIVATED", indPneu = "TPMS LOW PRESSURE WARNING",
                indFullBattery = "SOC AT 100% — CHARGING TERMINATED", indStopFirst = "VEHICLE MUST BE STATIONARY",
                indStopToGear = "ZERO VELOCITY REQUIRED FOR GEAR CHANGE", indTurnOnToGear = "IGNITION CYCLE REQUIRED",
                tripTitle = "TRIP TELEMETRY", tripDistance = "ODOMETER Δ", avgSpeed = "Ø VELOCITY", maxSpeed = "V-MAX", tripTime = "ELAPSED", avgConsumption = "Ø CONSUMPTION", resetTrip = "RESET TRIP", regenLabel = "REGEN", chargeTimeEst = "ETA FULL SOC",
                workInProgress = "Module under development..."
            )
            else -> base
        }
        AppLanguage.PT -> when (complexity) {
            "SIMPLE" -> base.copy(
                settingsTitle = "DEFINIÇÕES", bluetoothTitle = "TELEMÓVEL", bluetoothDesc = "Ligar o telemóvel ou auricular",
                connectTitle = "LIGAR APP", connectDesc = "Ligar a mota à aplicação",
                colorTitle = "COR", colorDesc = "Escolher uma cor que goste",
                elemColorTitle = "COR DOS ÍCONES", elemColorDesc = "Escolher a cor dos ícones",
                textColorTitle = "COR DAS LETRAS", textColorDesc = "Escolher a cor das letras",
                secTextColorTitle = "COR DO TEXTO PEQUENO", secTextColorDesc = "Escolher a cor do texto pequeno",
                langTitle = "IDIOMA", langDesc = "Escolher o idioma",
                persTitle = "APARÊNCIA", persDesc = "Mudar como as coisas aparecem",
                aboutTitle = "SOBRE", aboutDesc = "Informações sobre a sua mota",
                colorLibraryTitle = "ESCOLHER COR", dragColor = "Deslize para escolher a cor",
                activateIaTitle = "AJUDA INTELIGENTE", activateIaDesc = "Deixar o sistema ajudar automaticamente",
                visualPrefTitle = "ASPETO DO ECRÃ", visualPrefDesc = "Mudar cores e tamanho das letras",
                touchTitle = "TOQUE", touchDesc = "Mudar como o ecrã responde ao toque",
                cognitiveTitle = "AJUDA DE LEITURA", cognitiveDesc = "Tornar o ecrã mais fácil de ler",
                audioHapticsTitle = "SONS", audioHapticsDesc = "Mudar sons e vibrações",
                editIconsTitle = "MOVER ÍCONES", editIconsDesc = "Mover ícones de sítio",
                contrastTitle = "BRILHO", contrastDesc = "Tornar o texto mais visível",
                textSizeTitle = "TAMANHO DAS LETRAS", textSizeDesc = "Aumentar ou diminuir as letras",
                colorFiltersTitle = "AJUDA DE CORES", colorFiltersDesc = "Ajuda para quem vê mal as cores",
                textSpacingTitle = "ESPAÇO ENTRE LETRAS", textSpacingDesc = "Mais espaço entre as letras",
                animationsTitle = "EFEITOS", animationsDesc = "Desligar efeitos de movimento",
                touchSettingsTitle = "DEFINIÇÕES DE TOQUE", touchAreasTitle = "TAMANHO DOS BOTÕES", touchAreasDesc = "Tornar os botões maiores",
                methodTitle = "COMO USAR", methodDesc = "Escolher como usar o ecrã",
                responseTimeTitle = "RAPIDEZ", responseTimeDesc = "Rapidez com que o ecrã reage ao toque",
                errorPreventionTitle = "VERIFICAÇÃO", errorPreventionDesc = "Perguntar antes de fazer coisas importantes",
                langComplexityTitle = "DIFICULDADE DAS PALAVRAS", langComplexityDesc = "Usar palavras mais simples ou mais difíceis",
                infoDensityTitle = "QUANTA INFORMAÇÃO", infoDensityDesc = "Mostrar mais ou menos informação",
                contextHelpTitle = "DICAS", contextHelpDesc = "Mostrar dicas sobre o que as coisas fazem",
                alertsTitle = "AVISOS", alertsDesc = "Escolher que avisos ver",
                audioHapticsScreenTitle = "SONS E VIBRAÇÕES", feedbackDesc = "Escolher sons ou vibrações",
                visualAlertsTitle = "PISCAR ECRÃ", visualAlertsDesc = "Piscar o ecrã para sons importantes",
                errorFeedbackTitle = "FORÇA DO AVISO", errorFeedbackDesc = "Força do aviso quando há um erro",
                lowBattery = "BATERIA FRACA (20%)", critRange1 = "Bateria quase vazia. Por favor vá", critRange2 = "a um ponto de carregamento agora.",
                indBattery = "PROBLEMA NA BATERIA", indTempBat = "BATERIA MUITO QUENTE", indTempMotor = "MOTOR MUITO QUENTE",
                indBrake = "PROBLEMA NOS TRAVÕES", indMil = "PROBLEMA NO MOTOR", indAbs = "PROBLEMA NO ABS",
                indEsp = "AJUDA DE ESTABILIDADE DESLIGADA", indPneu = "PNEU VAZIO",
                indFullBattery = "BATERIA JÁ ESTÁ CHEIA", indStopFirst = "PARE A MOTA PRIMEIRO",
                indStopToGear = "PARE PARA MUDAR DE MARCHA", indTurnOnToGear = "LIGUE A MOTA PRIMEIRO",
                tripTitle = "INFO VIAGEM", tripDistance = "QUANTO FOI", avgSpeed = "VELOCIDADE MÉDIA", maxSpeed = "MAIS RÁPIDO", tripTime = "TEMPO", avgConsumption = "ENERGIA GASTA", resetTrip = "RECOMEÇAR", regenLabel = "ENERGIA DE VOLTA", chargeTimeEst = "FALTA",
                workInProgress = "Em breve..."
            )
            "TECHNICAL" -> base.copy(
                settingsTitle = "CONFIG. SISTEMA", bluetoothTitle = "EMPARELHAM. BT", bluetoothDesc = "Gerir emparelhamento BT 5.0 e links intercom",
                connectTitle = "SYNC OTA", connectDesc = "Sincronização OTA via ponte telemetria MyFulgora",
                colorTitle = "COR FUNDO (HEX)", colorDesc = "Selecionar fundo HEX/HSL da paleta",
                elemColorTitle = "TINT UI", elemColorDesc = "Modificar valores de tint dos elementos UI",
                textColorTitle = "TEXTO RGB PRIMÁRIO", textColorDesc = "Definir canal de cor RGB do texto primário",
                secTextColorTitle = "TEXTO RGB SECUNDÁRIO", secTextColorDesc = "Configurar saída de cor do texto secundário",
                langTitle = "LOCALE", langDesc = "Definir locale e idioma de exibição do sistema",
                persTitle = "CONFIG. HMI", persDesc = "Configurar layout HMI, unidades e escala",
                aboutTitle = "DIAGNÓSTICOS", aboutDesc = "Firmware ECU, VIN, diagnósticos barramento CAN",
                colorLibraryTitle = "ESPECTRO DE MATIZ", dragColor = "Arrastar pelo espectro de matiz (0-360°)",
                activateIaTitle = "UI ADAPTATIVA ML", activateIaDesc = "Ativar pipeline de UI adaptativa por ML",
                visualPrefTitle = "PARÂMETROS VISUAIS", visualPrefDesc = "Configurar contraste WCAG, escala de fontes e filtros",
                touchTitle = "CALIBRAÇÃO INPUT", touchDesc = "Calibrar entrada capacitiva e reconhecimento de gestos",
                cognitiveTitle = "CARGA COGNITIVA", cognitiveDesc = "Ajustar parâmetros de carga cognitiva do HMI",
                audioHapticsTitle = "FEEDBACK I/O", audioHapticsDesc = "Configurar canais de feedback áudio/háptico",
                editIconsTitle = "LAYOUT CLUSTER", editIconsDesc = "Reorganizar grelha de widgets do cluster",
                contrastTitle = "RÁCIO CONTRASTE", contrastDesc = "Definir rácio de contraste luminância WCAG 2.1 AAA",
                textSizeTitle = "ESCALA FONTE (SP)", textSizeDesc = "Ajustar fator de escala global de fonte (dp/sp)",
                colorFiltersTitle = "MATRIZES DVC", colorFiltersDesc = "Aplicar matrizes de simulação DVC (protanopia/deuteranopia)",
                textSpacingTitle = "ESPAÇAMENTO TIPOGRÁFICO", textSpacingDesc = "Modificar letter-spacing e line-height (em)",
                animationsTitle = "MULTIPLICADOR ANIM.", animationsDesc = "Configurar multiplicador de duração de animações",
                touchSettingsTitle = "PARÂMETROS INPUT", touchAreasTitle = "TAMANHO ALVO (DP)", touchAreasDesc = "Definir tamanho alvo mínimo WCAG (44dp/48dp)",
                methodTitle = "MODALIDADE INPUT", methodDesc = "Selecionar modalidade de entrada primária (capacitivo/swipe/HW)",
                responseTimeTitle = "DEBOUNCE (MS)", responseTimeDesc = "Configurar limiar de debounce tátil (ms)",
                errorPreventionTitle = "DIÁLOGOS CONFIRMAÇÃO", errorPreventionDesc = "Ativar diálogos de confirmação para comandos CAN críticos",
                langComplexityTitle = "REGISTO TERMINOLÓGICO", langComplexityDesc = "Definir registo terminológico (simples/padrão/técnico)",
                infoDensityTitle = "DENSIDADE TELEMETRIA", infoDensityDesc = "Configurar nível de densidade de telemetria",
                contextHelpTitle = "DOCS INLINE", contextHelpDesc = "Alternar documentação contextual inline do HMI",
                alertsTitle = "FILTRO DTC", alertsDesc = "Definir filtro de prioridade de notificações DTC",
                audioHapticsScreenTitle = "CONFIG. FEEDBACK I/O", feedbackDesc = "Selecionar modalidade de feedback de I/O do sistema",
                visualAlertsTitle = "FLASH VISUAL DTC", visualAlertsDesc = "Ativar flash visual em alertas DTC áudio",
                errorFeedbackTitle = "INTENSIDADE HÁPTICA", errorFeedbackDesc = "Definir intensidade do atuador háptico para eventos DTC",
                lowBattery = "SOC PACK HV CRÍTICO (≤20%)", critRange1 = "SOC abaixo do limiar mínimo. Navegue até", critRange2 = "infraestrutura EVSE mais próxima.",
                indBattery = "FALHA BATERIA HV — DTC P0A80", indTempBat = "RISCO THERMAL RUNAWAY DO PACK", indTempMotor = "TEMP. REFRIGERANTE ACIMA DO LIMIAR",
                indBrake = "FALHA CIRCUITO HIDRÁULICO DE TRAVAGEM", indMil = "MIL — DTC POWERTRAIN ATIVO", indAbs = "FALHA MÓDULO ABS — DTC C0035",
                indEsp = "ESC/TCS DESATIVADO", indPneu = "ALERTA TPMS — PRESSÃO BAIXA",
                indFullBattery = "SOC A 100% — CARREGAMENTO TERMINADO", indStopFirst = "VEÍCULO DEVE ESTAR ESTACIONÁRIO",
                indStopToGear = "VELOCIDADE ZERO REQUERIDA PARA MUDANÇA", indTurnOnToGear = "CICLO DE IGNIÇÃO NECESSÁRIO",
                tripTitle = "TELEMETRIA VIAGEM", tripDistance = "ODÓMETRO Δ", avgSpeed = "Ø VELOCIDADE", maxSpeed = "V-MAX", tripTime = "DECORRIDO", avgConsumption = "Ø CONSUMO", resetTrip = "REINICIAR TRIP", regenLabel = "REGEN", chargeTimeEst = "ETA SOC PLENO",
                workInProgress = "Módulo em desenvolvimento..."
            )
            else -> base
        }
        AppLanguage.ES -> when (complexity) {
            "SIMPLE" -> base.copy(
                settingsTitle = "AJUSTES", bluetoothTitle = "TELÉFONO", bluetoothDesc = "Conectar el teléfono o auricular",
                connectTitle = "CONECTAR APP", connectDesc = "Conectar la moto a la app",
                colorTitle = "COLOR", colorDesc = "Elegir un color que te guste",
                elemColorTitle = "COLOR ICONOS", elemColorDesc = "Elegir el color de los iconos",
                textColorTitle = "COLOR LETRAS", textColorDesc = "Elegir el color de las letras",
                secTextColorTitle = "COLOR TEXTO PEQUEÑO", secTextColorDesc = "Elegir el color del texto pequeño",
                langTitle = "IDIOMA", langDesc = "Elegir el idioma",
                persTitle = "ASPECTO", persDesc = "Cambiar cómo se ven las cosas",
                aboutTitle = "SOBRE", aboutDesc = "Información sobre tu moto",
                cognitiveTitle = "AYUDA DE LECTURA", langComplexityTitle = "DIFICULTAD PALABRAS", langComplexityDesc = "Usar palabras más fáciles o más difíciles",
                infoDensityTitle = "CUÁNTA INFO", infoDensityDesc = "Mostrar más o menos información",
                contextHelpTitle = "CONSEJOS", contextHelpDesc = "Mostrar consejos sobre qué hace cada cosa",
                alertsTitle = "AVISOS", alertsDesc = "Elegir qué avisos ver",
                indBattery = "PROBLEMA EN LA BATERÍA", indTempBat = "BATERÍA MUY CALIENTE", indTempMotor = "MOTOR MUY CALIENTE",
                indBrake = "PROBLEMA EN LOS FRENOS", indMil = "PROBLEMA EN EL MOTOR", indAbs = "PROBLEMA EN EL ABS",
                indEsp = "AYUDA DE ESTABILIDAD APAGADA", indPneu = "NEUMÁTICO DESINFLADO"
            )
            "TECHNICAL" -> base.copy(
                settingsTitle = "CONFIG. SISTEMA", bluetoothTitle = "EMPAREJAM. BT", bluetoothDesc = "Gestionar emparejamiento BT 5.0 y enlaces intercom",
                connectTitle = "SYNC OTA", connectDesc = "Sincronización OTA vía puente telemetría MyFulgora",
                colorTitle = "COLOR FONDO (HEX)", colorDesc = "Seleccionar fondo HEX/HSL de la paleta",
                persTitle = "CONFIG. HMI", cognitiveTitle = "CARGA COGNITIVA",
                langComplexityTitle = "REGISTRO TERMINOLÓGICO", langComplexityDesc = "Definir registro terminológico (simple/estándar/técnico)",
                infoDensityTitle = "DENSIDAD TELEMETRÍA", infoDensityDesc = "Configurar nivel de densidad de telemetría",
                contextHelpTitle = "DOCS INLINE", contextHelpDesc = "Alternar documentación contextual inline del HMI",
                alertsTitle = "FILTRO DTC", alertsDesc = "Definir filtro de prioridad de notificaciones DTC",
                indBattery = "FALLO BATERÍA HV — DTC P0A80", indTempBat = "RIESGO THERMAL RUNAWAY DEL PACK", indTempMotor = "TEMP. REFRIGERANTE SOBRE UMBRAL",
                indBrake = "FALLO CIRCUITO HIDRÁULICO DE FRENADO", indMil = "MIL — DTC POWERTRAIN ACTIVO", indAbs = "FALLO MÓDULO ABS — DTC C0035",
                indEsp = "ESC/TCS DESACTIVADO", indPneu = "ALERTA TPMS — PRESIÓN BAJA"
            )
            else -> base
        }
        AppLanguage.FR -> when (complexity) {
            "SIMPLE" -> base.copy(
                settingsTitle = "RÉGLAGES", bluetoothTitle = "TÉLÉPHONE", bluetoothDesc = "Connecter votre téléphone ou casque",
                connectTitle = "RELIER APP", connectDesc = "Relier votre moto à l'application",
                colorTitle = "COULEUR", colorDesc = "Choisir une couleur que vous aimez",
                persTitle = "APPARENCE", cognitiveTitle = "AIDE À LA LECTURE",
                langComplexityTitle = "DIFFICULTÉ DES MOTS", langComplexityDesc = "Utiliser des mots plus simples ou plus techniques",
                infoDensityTitle = "COMBIEN D'INFO", infoDensityDesc = "Montrer plus ou moins d'informations",
                contextHelpTitle = "CONSEILS", contextHelpDesc = "Montrer des conseils sur chaque fonction",
                alertsTitle = "ALERTES", alertsDesc = "Choisir quelles alertes voir",
                indBattery = "PROBLÈME DE BATTERIE", indTempBat = "BATTERIE TROP CHAUDE", indTempMotor = "MOTEUR TROP CHAUD",
                indBrake = "PROBLÈME DE FREINS", indMil = "PROBLÈME MOTEUR", indAbs = "PROBLÈME ABS",
                indEsp = "AIDE À LA STABILITÉ DÉSACTIVÉE", indPneu = "PNEU À PLAT"
            )
            "TECHNICAL" -> base.copy(
                settingsTitle = "CONFIG. SYSTÈME", bluetoothTitle = "APPAIRAGE BT", bluetoothDesc = "Gérer appairage BT 5.0 et liens intercom",
                connectTitle = "SYNC OTA", connectDesc = "Sync OTA via pont télémétrie MyFulgora",
                colorTitle = "COULEUR FOND (HEX)", colorDesc = "Sélectionner fond HEX/HSL depuis la palette",
                persTitle = "CONFIG. IHM", cognitiveTitle = "CHARGE COGNITIVE",
                langComplexityTitle = "REGISTRE TERMINOLOGIQUE", langComplexityDesc = "Définir registre terminologique (simple/standard/technique)",
                infoDensityTitle = "DENSITÉ TÉLÉMÉTRIE", infoDensityDesc = "Configurer niveau de densité télémétrie",
                contextHelpTitle = "DOCS INLINE", contextHelpDesc = "Basculer documentation contextuelle inline HMI",
                alertsTitle = "FILTRE DTC", alertsDesc = "Définir filtre priorité notifications DTC",
                indBattery = "DÉFAUT BATTERIE HV — DTC P0A80", indTempBat = "RISQUE EMBALLEMENT THERMIQUE PACK",
                indTempMotor = "TEMP. LIQUIDE REFROIDISSEMENT AU-DESSUS DU SEUIL", indBrake = "DÉFAILLANCE CIRCUIT HYDRAULIQUE FREINAGE",
                indMil = "MIL — DTC GROUPE MOTOPROPULSEUR ACTIF", indAbs = "DÉFAUT MODULE ABS — DTC C0035",
                indEsp = "ESC/TCS DÉSACTIVÉ", indPneu = "ALERTE TPMS — PRESSION BASSE"
            )
            else -> base
        }
        AppLanguage.DE -> when (complexity) {
            "SIMPLE" -> base.copy(
                settingsTitle = "EINSTELLUNGEN", bluetoothTitle = "TELEFON", bluetoothDesc = "Telefon oder Headset verbinden",
                connectTitle = "APP VERBINDEN", connectDesc = "Motorrad mit der App verbinden",
                colorTitle = "FARBE", colorDesc = "Eine Farbe auswählen, die Ihnen gefällt",
                persTitle = "AUSSEHEN", cognitiveTitle = "LESEHILFE",
                langComplexityTitle = "WORTSCHWIERIGKEIT", langComplexityDesc = "Einfachere oder schwierigere Wörter verwenden",
                infoDensityTitle = "INFOMENGE", infoDensityDesc = "Mehr oder weniger Informationen anzeigen",
                contextHelpTitle = "TIPPS", contextHelpDesc = "Tipps zeigen, was die Dinge tun",
                alertsTitle = "WARNUNGEN", alertsDesc = "Wählen Sie welche Warnungen Sie sehen",
                indBattery = "BATTERIEPROBLEM", indTempBat = "BATTERIE ZU HEISS", indTempMotor = "MOTOR ZU HEISS",
                indBrake = "BREMSPROBLEM", indMil = "MOTORPROBLEM", indAbs = "ABS-PROBLEM",
                indEsp = "STABILITÄTSHILFE AUS", indPneu = "REIFEN PLATT"
            )
            "TECHNICAL" -> base.copy(
                settingsTitle = "SYSTEMKONFIG.", bluetoothTitle = "BT-KOPPLUNG", bluetoothDesc = "BT 5.0-Kopplung und Intercom-Links verwalten",
                connectTitle = "OTA-SYNC", connectDesc = "OTA-Sync über MyFulgora Telemetrie-Brücke",
                colorTitle = "HINTERGRUND (HEX)", colorDesc = "HEX/HSL-Hintergrund aus Palette auswählen",
                persTitle = "HMI-KONFIG.", cognitiveTitle = "KOGNITIVE LAST",
                langComplexityTitle = "TERMINOLOGIEREGISTER", langComplexityDesc = "Terminologieregister festlegen (einfach/standard/technisch)",
                infoDensityTitle = "TELEMETRIEDICHTE", infoDensityDesc = "Telemetrie-Dichtestufe konfigurieren",
                contextHelpTitle = "INLINE-DOKS", contextHelpDesc = "Inline-Kontextdokumentation HMI umschalten",
                alertsTitle = "DTC-FILTER", alertsDesc = "DTC-Benachrichtigungsprioritätsfilter festlegen",
                indBattery = "HV-BATTERIEFEHLER — DTC P0A80", indTempBat = "PACK THERMAL RUNAWAY RISIKO",
                indTempMotor = "KÜHLMITTELTEMP. ÜBER SCHWELLENWERT", indBrake = "HYDRAULISCHER BREMSKREISAUSFALL",
                indMil = "MIL — ANTRIEBSSTRANG DTC AKTIV", indAbs = "ABS-MODULFEHLER — DTC C0035",
                indEsp = "ESC/TCS DEAKTIVIERT", indPneu = "TPMS-WARNUNG — NIEDRIGER DRUCK"
            )
            else -> base
        }
        AppLanguage.IT -> when (complexity) {
            "SIMPLE" -> base.copy(
                settingsTitle = "IMPOSTAZIONI", bluetoothTitle = "TELEFONO", bluetoothDesc = "Collegare il telefono o le cuffie",
                connectTitle = "COLLEGA APP", connectDesc = "Collegare la moto all'app",
                colorTitle = "COLORE", colorDesc = "Scegliere un colore che ti piace",
                persTitle = "ASPETTO", cognitiveTitle = "AIUTO LETTURA",
                langComplexityTitle = "DIFFICOLTÀ PAROLE", langComplexityDesc = "Usare parole più semplici o più difficili",
                infoDensityTitle = "QUANTE INFO", infoDensityDesc = "Mostrare più o meno informazioni",
                contextHelpTitle = "SUGGERIMENTI", contextHelpDesc = "Mostrare suggerimenti su cosa fa ogni cosa",
                alertsTitle = "AVVISI", alertsDesc = "Scegliere quali avvisi vedere",
                indBattery = "PROBLEMA ALLA BATTERIA", indTempBat = "BATTERIA TROPPO CALDA", indTempMotor = "MOTORE TROPPO CALDO",
                indBrake = "PROBLEMA AI FRENI", indMil = "PROBLEMA AL MOTORE", indAbs = "PROBLEMA ALL'ABS",
                indEsp = "AIUTO STABILITÀ DISATTIVATO", indPneu = "PNEUMATICO SGONFIO"
            )
            "TECHNICAL" -> base.copy(
                settingsTitle = "CONFIG. SISTEMA", bluetoothTitle = "ACCOPPIAMENTO BT", bluetoothDesc = "Gestire accoppiamento BT 5.0 e link intercom",
                connectTitle = "SYNC OTA", connectDesc = "Sincronizzazione OTA via ponte telemetria MyFulgora",
                colorTitle = "COLORE SFONDO (HEX)", colorDesc = "Selezionare sfondo HEX/HSL dalla palette",
                persTitle = "CONFIG. HMI", cognitiveTitle = "CARICO COGNITIVO",
                langComplexityTitle = "REGISTRO TERMINOLOGICO", langComplexityDesc = "Impostare registro terminologico (semplice/standard/tecnico)",
                infoDensityTitle = "DENSITÀ TELEMETRIA", infoDensityDesc = "Configurare livello densità telemetria",
                contextHelpTitle = "DOCS INLINE", contextHelpDesc = "Attivare documentazione contestuale inline HMI",
                alertsTitle = "FILTRO DTC", alertsDesc = "Impostare filtro priorità notifiche DTC",
                indBattery = "GUASTO BATTERIA HV — DTC P0A80", indTempBat = "RISCHIO THERMAL RUNAWAY PACK",
                indTempMotor = "TEMP. REFRIGERANTE SOPRA SOGLIA", indBrake = "GUASTO CIRCUITO IDRAULICO FRENATA",
                indMil = "MIL — DTC POWERTRAIN ATTIVO", indAbs = "GUASTO MODULO ABS — DTC C0035",
                indEsp = "ESC/TCS DISATTIVATO", indPneu = "ALLARME TPMS — PRESSIONE BASSA"
            )
            else -> base
        }
    }
}